### ISSUE TITLE
package build fails

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#1]
When trying to build the package, I get the following error:
fatal error: RcppArmadillo.h: No such file or directory
 #include <RcppArmadillo.h>

**Comment by marcinjurek** [comment]
@wenlongG what's the status here? Is this still a problem?

**Comment by marcinjurek** [comment]
I cleaned my local repo and the package cannot even be built using R CMD build. Need to resolve this first.

**Comment by marcinjurek** [comment]
try building the package using the best practices outlined in http://r-pkgs.had.co.nz/src.html

**Comment by marcinjurek** [comment]
The error right now is that when using an installed version of the package, the solve() function in createU() does not return a sparse matrix. When the same code is sourced instead, it works fine

**Comment by marcinjurek** [comment]
as of 992c403 the library can now be build using R CMD build

**Comment by katzfuss** [comment]
Great, thank you. Please test that this way of installing does not affect (i.e., slow down) the code execution for, say, n=40,000, m=20 relative to "manual" installation (sourcing). 
If everything works well, should we update the installation instructions in the GPvecchia readme?

**Comment by marcinjurek** [comment]
just a short update here. @katzfuss thanks for mentioning testing for speed because using the installed version of the package turned out to be indeed much slower. It is baffling to me why, but I managed to identify that the problem is in the vecchia_lieklihood_U function. When run on my laptop it crashes due to insufficient memory (though it doesn't say exactly at which line). Run the server it does not crash but takes much longer to return. Apparently the problem is in converting to a Matrix but the error message was very cryptic and I have to time it line by line.

**Comment by dzilber** [comment]
I am also playing with this packaged version that is created by install_github.  I did a profiling test with the `calculate_posterior_VL` function and found that most of the time is being spent on the command `solve.default` in the vecchia_mean function.  

I checked what @marcinjurek is getting and can reproduce it with a call to `vecchia_likelihood`. Most of the time for this call is also being spent in some `solve.default` function, this time in `vecchia_likelihood_U`.

To add to the mystery, the Laplace version of the VL code fails with the message `Error in solve.default(D + C, t)`.  It would seem that the `solve` function is the source of our problems.

**Comment by dzilber** [comment]
I have a guess that we want R to use the `solve` command from the Matrix package, rather than the R base.  Replacing `solve` with `Matrix::solve` got rid of the issue in the Laplace code I have, will test with the other vecchia methods.

**Comment by marcinjurek** [comment]
hey, I think I solved it! So all calls to the regular matrix functions (like `t()`, `diag`, `chol` had to be prefixed by `Matrix::`).

**Comment by marcinjurek** [comment]
Please @dzilber test on your end to double check and lmk or just close the ticket! Hey thanks for yout help by the way! Your hints were really really helpful!

**Comment by dzilber** [comment]
The code is getting faster, nice work @marcinjurek!  I still see most of the time spent in some solve routine, rather than U_NZentries as in the regular case, for both the VL code and the regular Vecchia vignette.  We can't close this yet.

**Comment by marcinjurek** [comment]
Oh... ok, well I compared only vecchia_likelihood functions. Yes, you're right! I'm on it!

**Comment by marcinjurek** [comment]
actually could you go through the `vecchia_laplace_NR.R` file? I don't know it that well and wouldn't want to mess things up.

**Comment by dzilber** [comment]
Yep, I'll handle the `vecchia_laplace_NR.R` @marcinjurek

**Comment by marcinjurek** [comment]
vignettes for regular and hierarchical vecchia (mra) run fine!

**Comment by dzilber** [comment]
This is working for the VL vignette as well using `devtools::install_local`.  The Laplace-only prediction is slow and could probably be corrected further, but it is not relevant to this ticket.  Thanks @marcinjurek !
