### ISSUE TITLE
Vecchia-Laplace: restructure function

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#12]
It might be useful to structure the VL code more along the lines of the vecchia code for Gaussian data:

> vecchia.approx=vecchia_specify(z,locs,m,ordering,cond.yz,locs.pred,ordering.pred,pred.cond,conditioning)
calculate_posterior_VL = function(vecchia.approx,likelihood_model, covparms, max.iter=50, convg = 1e-6) {
...
for(i in 1:max.iter){
...
NOTE: do not use vecchia_prediction() here, as it computes the posterior variances every time. Instead:
U=createU(vecchia.approx,covparms,nuggets,covmodel)
V.ord=U2V(U,vecchia.approx)
vecchia.mean=vecchia_mean(vecchia.approx,U,V.ord)
...
}
return posterior.mode, U, V
}
then, quantities of interest such as likelihood, posterior variances, ... can be calculated outside of calculate_posterior_VL using the existing functions for the Gaussian case

Structuring the code this way will make it more consistent with the existing code. This would also allow us to debug the VL code more easily, by choosing likelihood_model to be Gaussian, and comparing it to the output from the existing code with the exact same vecchia.approx object.

Also, could you please add a vignette showing how to use the VL functions to the vignettes/ folder? It should look very similar to the existing vignette for Gaussian data.

Thank you!

**Comment by katzfuss** [comment]
Great, thank you!

This made cause problems in 2 or higher dimensions when locs should be a matrix with more than one column:

> locs = vecchia.approx$locsord[orig_ord]

Also, is the code now actually using the ordering implied by specify_vecchia()? If not, the approximation might be poor in two dimensions, or more generally if the locations are not ordered appropriately from the start.

**Comment by katzfuss** [comment]
Please make sure to always test the 1-D and 2-D case before committing.

**Comment by dzilber** [comment]
It seemed to be working fine but I agree that the quoted line should not work.  I'll fix that and recommit.

**Comment by dzilber** [comment]
I'm not sure why it worked with 2D before, but I made the following change (added a comma) that I believe should handle arbitrary dimension:
`  locs = vecchia.approx$locsord[orig_ord,]`
