### ISSUE TITLE
U_NZentries.cpp should be able to handle NAs in revNNarray

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#16]
In U_NZentries.cpp, inds00 is currently calculated assuming that revNNarray always has the same NA pattern, in which any rows after the first m do not have any NAs. It should be changed such that it can automatically handle NAs in arbitrary locations correctly, by simply not including them in inds00. Specifically, it should work even if a lot of rows consist only of NAs (except for the last element in each row).

Once this is completed, line 129 in vecchia_specify.R can be changed for more efficiency.

**Comment by dzilber** [comment]
Testing MSE looked reasonable for the four likelihoods and 1 or 2 dimensions.  Running 40,000 data points, covparm = (1, 0.1, 0.5), m=10, 2D poisson on [0,1]^2, avg for 2 runs:
zy: ~ 7 seconds per iteration, 10 iterations 
SGV:  ~6.2 seconds per iteration, 9 iterations
