### ISSUE TITLE
incorret path in readme

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#18]
It seems to me, that we should change the path given in the Installation section of the README.md file. Currently, the command that's supposed to install the package form a tarball is 

```{R}
install.packages("~/GPvecchia_0.1.tar.gz", repos = NULL, type = "source")
```

which presumes that `GPvecchia_0.1.tar.gz` is in the home directory. Maybe we should change it to:

```{R}
install.packages("GPvecchia_0.1.tar.gz", repos = NULL, type = "source")
```

which assumes the archive is in the current working directory

**Comment by katzfuss** [comment]
Yes, please change.

**Comment by marcinjurek** [comment]
oh, ok. I wasn't aware I had write access here.
