### ISSUE TITLE
Matern function not found

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#19]
I recently had to reinstall R and after I did it, I tried to run the vignettes. I tried installing GPvecchia using both `install_github` and `install.packages("GPvecchia_0.1.tar.gz", repos = NULL, type = "source")` and each time I'm getting the following error:
```
Error in Matern(fields::rdist(locs), range = range, smoothness = smooth) : 
  could not find function "Matern"
```
Please advise.

**Comment by wenlongG** [comment]
I've updated the vignettes file to make the MaternFun name and input consistent with its definition in rcpp.  Try it again, that error should be gone.

**Comment by marcinjurek** [comment]
Works! thanks Wenlong!
