### ISSUE TITLE
error in U_sparsity for MRA conditioning

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#21]
Hello everyone, so here is the problem I've encountered. I'm trying to specify MRA conditioning in `vecchia_specify.R`. When I order locations in 1d left to right I am able to obtain the domain partitioning, knots and NN array as in the second screen shot. 

However, when this NNarray is used within `vecchia_specify.R`, the following error is thrown:

![err](https://user-images.githubusercontent.com/6467709/47865780-19750880-ddcb-11e8-9334-cd7d3da3d814.png)

![screenshot_20181101_113409](https://user-images.githubusercontent.com/6467709/47865627-aff4fa00-ddca-11e8-9c4c-0e8b3efba10e.png)

I'm posting it here, b/c I don't know the U_sparsity function very well yet. I am going to try to debug it myself, but if anyone could give me some clues what the problem could be, it would help a lot! Thanks!

**Comment by katzfuss** [comment]
The i-th row of the NNarray matrix specifies on which locations the i-th location conditions. The first entry of the i-th row should be i, which is correct in your matrix. However, the other numbers in the row should always be smaller than i, as every location can only condition on previously ordered locations. So, for example, row 1 always consists of the number 1 and then only NAs, as nothing is ordered before location 1. Row 4 cannot have a 5 in it as in your example, etc.

**Comment by marcinjurek** [comment]
Oh, oh, I see! Alright, that makes sense now, thanks a lot.
