### ISSUE TITLE
Method U2V() uses vecchia.approx object from the Global env

### ISSUE THREAD

**Issue by dzilber** [katzfuss-group/GPvecchia#23]
The method U2V() in vecchia_prediction references an attribute of a vecchia.approx object which is not passed in.  The fix discussed with @katzfuss is to add the attribute, vecchia.approx$ord.pred, to the U matrix generated in the createU() method.

**Comment by marcinjurek** [comment]
I realized that too. I fixed it in my local copy by changing the call to `U2V` in `vecchia_likelihood_U()` from
`V.ord=U2V(U.obj)`
to 
`V.ord=U2V(U.obj, ord.pred=parent.frame()$vecchia.approx$ord.pred)`.

**Comment by marcinjurek** [comment]
By the way the most recent push included that fix. Let me know if that's not okay asap.

**Comment by katzfuss** [comment]
I discussed a different, preferred solution with @dzilber last week. Daniel, please push your solution and tell Marcin the details.

**Comment by marcinjurek** [comment]
done!
