### ISSUE TITLE
Add VecchiaLaplace wrappers for vecchia_likelihood and vecchia_prediction

### ISSUE THREAD

**Issue by dzilber** [katzfuss-group/GPvecchia#25]
The vecchia_likelihood and vecchia_prediction methods are both written for Gaussian data.  The VL versions are not trivial changes, but do build off of the base methods, so a wrapper will be made for both methods.

**Comment by dzilber** [comment]
First commit does not work yet but it is not clear where the issue is.  This commit should not change any existing functionality outside of VL.

**Comment by katzfuss** [comment]
These functions should also compute the posterior mode, and hence should have the same arguments as calculate_posterior_VL(). 

By the way, calculate_posterior_VL() should also have an argument called 'covmodel'.

**Comment by dzilber** [comment]
I am having issues with the `vecchia_likelihood` function.  The `na.rm()` function is looking at the `z` variable to determine if any `NA`'s are present in the `U.obj$U` object.  In my case the `z` does not have `NA` but the `U.obj$U` does.  

```
z_pseudo = posterior$t
nuggets_pseudo = posterior$D
vecchia_approx_IW = vecchia_specify(locs, m)
pseudo_marginal_loglik_vecchia = vecchia_likelihood(z_pseudo, vecchia_approx_IW,
                                                      covparms,nuggets_pseudo, covmodel)
```

The above fails at the step `logdet.num=-2*sum(log(Matrix::diag(U)))`, where `U=U.obj$U` still has `NA`'s that were not removed with `na.rm()` earlier.  

@katzfuss or @marcinjurek:  If you guys have any idea what is going on, let me know.

**Comment by marcinjurek** [comment]
hm... do you think you could post a reproducible example? or it would be enough if you just tell me the place in one of the existing files, where I should paste your code above.

**Comment by marcinjurek** [comment]
shoot, sorry, I didn't mean to close it:)

**Comment by dzilber** [comment]
I was just working on this and think the issue was related to the `locs` object.  I was trying to pull it out of another vecchia.approx object, but the command `locs = vecchia.approx$locsord` for my setup returned a list with each location duplicated, which is where the `NA`'s were coming from.   Don't worry about it for now, I'll let you know if I can't get it working.

**Comment by dzilber** [comment]
I implemented these changes a few weeks ago and have solved and problems I encountered.  As far as I can tell, this is working correctly, so I will close the ticket.
