### ISSUE TITLE
Known issues with MRA parameter settings

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#31]
- [ ] M=1, J=7, m=10: domain partitions do not seem to be contiguous
- [x] small m, i.e. m=4, n=80: the `choose.M` function uses the "small `m`" variant which results in effective m being typically very large
- [ ] n=1000; r=2; m=14

please add more issues by updating the ticket

**Comment by katzfuss** [comment]
I have just re-organized the MRA code into a single file in the main R folder.

Most MRA settings do no work for me. Running your vignette with n=50, 1D:

`mra.options = list(r=c(0,5), J=10, M=1)`
Returns: "Error in xy.coords(x, y) : 'x' and 'y' lengths differ." The error might actually be in the plotting function.

`mra.options = list(r=c(0,5))`
Works, but sets r_1 = 25, J=2, instead of specifying r_1=5, J=10.

`mra.options = list(M=1,J=10)`
Returns "Error in findOrderedNN_mra(locsord, m, mra.options) :  argument "m" is missing, with no default"

`vecchia_specify(locs, m=20,conditioning='mra')`
Returns "Error in get.mra.params: $ operator is invalid for atomic vectors "

In general, the vecchia_specify() function should not produce a plot by default, as this would take a long time for large n. You could write a plot_mra() function that would be run as follows:
```
vecchia.approx=vecchia_specify(locs,m=10,conditioning='mra')
plot_mra(vecchia.approx)
```

**Comment by katzfuss** [comment]
2) If n=50, we can only achieve r=c(0,5) if J=10. It would be good if our code would automatically recognize that.

**Comment by katzfuss** [comment]
Contrary to what I said earlier, I do think we need to allow for J>4 for resolution M, even if M>1. This would allow us to run a "reasonable" MRA even for small-ish m. Consider the following setting:
```
n=1000
V = vecchia_specify(locs, m=14,conditioning='mra',mra.options=list(M=2))
```
Currently, this sets J=2 and r=(14+1)/(2+1)=5 for resolutions 0 and 1, which is good. However, for resolution 2, we then have only 4 subregions with r_2 around (1000-15)/4=246. 
I think it would be much better if the default was instead to ensure m=14 by requiring that r_2=5, which would mean that J_2 should be set to (1000-15)/5=197. As we currently only allow powers of 2, we would use J_2 = 2^8 = 256.

**Comment by katzfuss** [comment]
Unless m, M, r, and J are all explicitly specified by the user, I think it would be useful if we always print the  m, M, r, and J that were selected by our algorithm.

**Comment by marcinjurek** [comment]
Dr. Katzfuss, I've just pushed the update that should fix most of the issues you mentioned in ticket 31. The one big one that's not addressed is allowing J!=2,4 at M>1. I went back and forth between different ideas I thought would solve it, but haven't figured it out just yet.As a temporary remedy, maybe you could try setting only r and m (and not M). Then M will be adjusted to allow for more splits and more resolutions.

Please add here any further issues you encounter. It's very helpful to have them all in one place as we do now.

**Comment by katzfuss** [comment]
Thank you! Most things are working well now. The most important issue is of course allowing J!=2,4 at M>1.

I also sometimes get the warning:

> In r * cumprod(J) :   longer object length is not a multiple of shorter object length


Another minor issue: The reported parameter settings should be the actual, final settings. Example:
```
n=500
mra.options = list(plots=TRUE, r=c(0,10))
V = vecchia_specify(locs, conditioning='mra',mra.options=mra.options)
```
Returns:

> [1] "MRA params: m=0, J=50, r=0,10, M=1"
> [1] "effective m: 7"
> the number of subregions fo the original domain is 50 but has to be a power of 2. Setting J=64.

-> So we really have m=7 and J=64. (And r is also smaller than 10.)

**Comment by katzfuss** [comment]
Some code below 
`NNarray = findOrderedNN_mra(locsord, m, mra.options)`
in vecchia_specify() relies on m being set correctly. Hence, please put the following line right below the NNarray computation for MRA:
`m=ncol(NNarray)-1`

Also, m should not be set to 0 by default. We should return an error if m is not specified, unless conditioning=='mra' and mra.options are specified. Currently, m=0 actually is not supported (see #30 ).

**Comment by marcinjurek** [comment]
Alright, I think I nailed it! The J[M]!=2 case should be resolved now!

**Comment by katzfuss** [comment]
`n=150; V = vecchia_specify(locs, m=6, conditioning='mra')`
returns a warning:

> In r * cumprod(J) :  longer object length is not a multiple of shorter object length

`n=150; V = vecchia_specify(locs, m=10, conditioning='mra')`
returns:

> Error: $ operator is invalid for atomic vectors

`n=30^2; vecchia_specify(locs,conditioning='mra',mra.options=list(r=c(0,11)))`

> Error in vecchia_specify(locs, conditioning = "mra", mra.options = list(r = c(0,  :   m not defined

`n=30^2; vecchia_specify(locs,m=10,conditioning='mra',mra.options=list(r=c(0,11)))`

>  Error in log(K, 2) : unused argument (2) 
> cluster.equal(locs, K = J) at domain-tree.r#136

`n=30^2; vecchia_specify(locs,m=10,conditioning='mra')`

>  Error in par.locs[, 1] : incorrect number of dimensions 
> quantile(par.locs[, 1], 0.5) at domain-tree.r#106


Once you have addressed these issues, please start cleaning up the code: Move all code to R folder (delete MRA folder), write vignette for a general audience (see GPvecchia_vignette as example).

**Comment by marcinjurek** [comment]
All these errors have been fixed on my end. I also ran the unit tests I came up with in #26. Let me test it more extensively tomorrow and reorganize the code too.

**Comment by katzfuss** [comment]
I'm still getting an error with this setting:
```
spatial.dim=2
n=1500
V = vecchia_specify(locs, m=10, conditioning='mra')
```
returns:
`Error in log((n - sum(2^(0:(M - 1))))/2^(M - 1), 2) : unused argument (2)`
in choose.M().

I think the issue is because the fields package overrides the log() function. The fields package is needed for some functions in GPvecchia.

**Comment by katzfuss** [comment]
log() issue is solved now.

The following settings still return errors:
```
n=30^2
grid.oneside=seq(0,1,length=round(sqrt(n)))
locs=as.matrix(expand.grid(grid.oneside,grid.oneside))
vecchia.approx=vecchia_specify(locs,m=2,conditioning='mra',mra.options=list(r=c(0,3)))
vecchia.approx=vecchia_specify(locs,m=1,conditioning='mra')
vecchia.approx=vecchia_specify(locs,m=5,conditioning='mra')
```

**Comment by marcinjurek** [comment]
#1e48794 should fix it. Closing the ticket now

**Comment by marcinjurek** [comment]
@katzfuss pushed an update. The code worked for all these different parameter settings on my end now.

@joeguinness Thanks, we've realized just that:) You're right about changing the rdist calls though

**Comment by marcinjurek** [comment]
imports of fields removed in #5d47290. Closing this ticket now.

**Comment by katzfuss** [comment]
```
n=30^2
grid.oneside=seq(0,1,length=round(sqrt(n)))
locs=as.matrix(expand.grid(grid.oneside,grid.oneside))
vecchia_specify(locs,15,conditioning='mra',mra.options=list(r=c(0,16)))
```
returns an error saying that some clusters are too big.

Another issue:
```
vecchia_specify(locs,m=3,cond.yz='SGV',conditioning='mra')
vecchia_specify(locs,m=3,cond.yz='y',conditioning='mra')

```
The first version with the default cond.yz='SGV' works, while the second version returns an error generated by line 47 in U_sparsity.R. This is weird, because cond.yz='SGV' and cond.yz='y' should be exactly equivalent in this setting, and as far as I could tell, both versions pass the exact same Cond object in vecchia_specify() to the U_sparsity() function.

**Comment by marcinjurek** [comment]
So I have looked at the first issue so far and I'm not sure what's wrong here. Of course, I can easily remove the line that's generating the error but the problem is that the biggest clusters are really too big (i.e. if they should have at most 15 points, some of them have 16. This is somehow related to the way we split the domain. It's not yet clear to me how to fix it.

I haven't look at the second issue but it's bizarre because cond.yz should be independent of the NNarray... 

That's all I can say for now, will keep working on it

**Comment by katzfuss** [comment]
Yes, maybe the fix for the first issue is to simply return a warning, not an error.

**Comment by marcinjurek** [comment]
So regarding the first issue, I changed the error to warning per your suggestion. This is a temporary solution. I need to make sure that cluster size is as it should be. The code should run but the oversized clusters cause `m` to be off by 1. 

Here is what I have on the second issue so far. I made sure that:
1) both cases generate the exact same `NNarray`
2) that indices in the first column are just row numbers
3) that no index in the columns 2 and beyond is greater than the row number (which ensures we condition on the previous observations). 

It seems that, when `cond.yz='y'`, the code makes some additional assumption on the `NNarray` that we are not aware of. Or can you think of any other requirements `NNarray` should satisfy that  (1)-(3) doesn't cover? 

I'll keep looking into it.

**Comment by katzfuss** [comment]
Yes, the NNarray seems to be good, and the same in both cases. What I don't understand is that U_sparsity() returns an error in the 'y' case but not in the 'SGV' case, even though the input to the function seems to be exactly the same in both cases.

**Comment by katzfuss** [comment]
@marcinjurek  Thanks for fixing the cluster size issue. 

I found two more settings that give errors:
```
n=60^2
grid.oneside=seq(0,1,length=round(sqrt(n)))
locs=as.matrix(expand.grid(grid.oneside,grid.oneside))
vecchia.approx=vecchia_specify(locs,m=20,conditioning='mra')

```
and
```
vecchia.approx=vecchia_specify(locs,m=15,conditioning='mra',mra.options=list(r=c(0,16)))
vecchia_likelihood(z,vecchia.approx,covparms,nugget)
```

**Comment by dzilber** [comment]
For `locs` a data set with ~150k points,
```
m=10
vecchia.approx.LR = vecchia_specify(locs, m, conditioning = "firstm")
```
gives
```
Error in if (mra.params$J != 2 && mra.params$J != 4) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In get.mra.params(n, mra.options, m) :
  M, r set for MRA. If parameter m was given, it will be overridden
```

Including a parameter `J=2` in the mra.options list gave
```
Error in rep(padding, a.width * a.height) : invalid 'times' argument
In addition: Warning messages:
1: In get.mra.params(n, mra.options, m) :
  M, r set for MRA. If parameter m was given, it will be overridden
2: In a.width * a.height : NAs produced by integer overflow
```

@marcinjurek This is blocking my work, so please correct the defaults for 'firstm' ASAP.  If you think it will take more than a day or two, let me know and I'll revert to an older version.

**Comment by marcinjurek** [comment]
@dzilber I'm sorry it's blocking your work. Unfortunately, I really don't have the pipeline to address it right now. I'm finishing a fix for Dr. Katzfuss and flying to Poland tomorrow. Hope you can manage without it somehow

**Comment by katzfuss** [comment]
@dzilber Please just revert to the old firstm code locally, but please do not push this, so that the master branch stays on the current version that uses MRA for firstm.

@marcinjurek  Please fix Daniel's issue once you have fixed the other MRA issues.

**Comment by marcinjurek** [comment]
Dr @katzfuss, I've just pushed an update. Domain partitioning is fixed.

**Comment by katzfuss** [comment]
With n=300^2, I'm getting:
Error: cannot allocate vector of size 1024 Kb 
6.
unique.default(if (length(x) || length(y)) x[match(x, y, 0L) == 
    0L] else x) 
5.
unique(if (length(x) || length(y)) x[match(x, y, 0L) == 0L] else x) 
4.
setdiff(remaining[[parent(ind)]], knots[[ind]]) at MRA_knot-tree.r#31
3.
knot.tree(ind.tree, mra.params[["r"]], dim = ncol(locs)) at mraNN.r#101
2.
findOrderedNN_mra(locsord, mra.options, m) at vecchia_specify.R#101
1.
vecchia_specify(locs, m, cond.yz = c1, conditioning = c2, mra.options = mra.opt)

**Comment by marcinjurek** [comment]
does it work for smaller data sets though?

**Comment by katzfuss** [comment]
yes

**Comment by marcinjurek** [comment]
could you send me all the parameters, please? I am trying it on my end on this many points. Hasn't finished yet but hasn't thrown this error either

**Comment by marcinjurek** [comment]
closing this ticket now, I will open a new one for the memory-efficient version
