### ISSUE TITLE
memory-efficient version of the MRA tree construction

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#33]
As indicated in #26 the current version of the tree construction causes memory issues for grids of size >= 90k. The solution that's adopted so far is to avoid building a grid point hierarchy before the knot hierarchy is created. The branch `memory-eff-tree` has this fix. Please report all errors here.

**Comment by marcinjurek** [comment]
The new algorithm works fine in the sense of not using too much memory but it has unacceptable runtime. For example it takes about 7s to build the `NNmatrix` when `m=20` and `n=90000`. After running the profiler (`profvis`, so far it's been a very easy-to-use and effective tool!), it seems to me that the parts of the code that take the most are have to do with list assignment. Check out this screenshot (generated when using `n=90000`):
![screenshot_20190107_145750](https://user-images.githubusercontent.com/6467709/50793185-fb28fe80-128c-11e9-8e0b-9cbd5671d5d3.png)
As far as I can understand it, accessing elements of lists by their index has linear complexity in R. Constant time access (like in hash maps) is not supported for any basic data structure in R (as far as I can tell). Another problem is that removing the first two elements from the list also doesn't work too fast. 

To conclude, I cannot see any reasonable workaround within the scope of R and it seems to be that the best solution is to write the whole thing in Rcpp

**Comment by marcinjurek** [comment]
Using environments as hash maps and the `dequer` package I was able to bring down the tree construction time for 330**2 ~ 1,000,000 points to 4.5 minutes and for 10,000 points to 2.5s. While a truly efficient solution would require some C++ coding, maybe this will suffice for now.

**Comment by katzfuss** [comment]
Yes, that's great, good job! I'm closing the issue.
