### ISSUE TITLE
vecchia_specify doesn't work after merge

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#34]
Dr. @katzfuss, after I merged my code with the most up-to-date version of the remote master my test code stopped working. In particular the problem is in `vecchia_specify()`. It says:
```{bash}
Error in cur_cols[revCond] <- latent_map[inds0[revCond]] : 
  NAs are not allowed in subscripted assignments
```
And this is thrown by the call to `U_specify()`. Is there something I should keep in mind when calling `vecchia_specify()`? I do it like this:
```{R}
V = vecchia_specify(locs, m=20, conditioning='mra')
```
When I use the verision of `vecchia_specify.R` that doesn't have the changes you made in de0a5aa and 21293bf it seems to work fine. Please advise.

**Comment by katzfuss** [comment]
I think this might be caused by #32 . If so, then
`vecchia_specify(locs, m=20, conditioning='mra',cond.yz = 'SGV')`
should work.

**Comment by marcinjurek** [comment]
It did! Alright, will look at #32 then
