### ISSUE TITLE
Exact max-min ordering code

### ISSUE THREAD

**Issue by dzilber** [katzfuss-group/GPvecchia#35]
As described by @katzfuss:
> For the Vecchia prediction paper (and the VL paper), it would be great if you could write a wrapper to call the C code from R in vecchia_specify() and replace the current approximate maxmin algorithm. It would also be great if the exact algorithm could be extended to ensure the obs-pred ordering restriction for predictions, if desired. But if it is too complicated, we could just do the exact maxmin for the observed locations, and then do the current approximate algorithm for the prediction locations.

**Comment by katzfuss** [comment]
Does it work if you run the C code outside of R?

**Comment by katzfuss** [comment]
@jingjiezh has found and corrected some bugs in the C code. Please work together to wrap this function in R. This should be highest priority at the moment.

**Comment by dzilber** [comment]
The first update is up.  The obs-pred ordering will now be attempted.

**Comment by dzilber** [comment]
Obs-pred ordering heuristic has been implemented by copying the code of the previous version.  Results seem to be nearly identical to the previous code for 1 and 2D tests with GPVecchia.  For a sample size of 40^2, the time to run vecchia_specify decreased by about 40%, from roughly .3 seconds to about .18 seconds.  

An exact obs-pred ordering will likely require modifying the c code and does not seem to be a priority, so this ticket will be closed and a new ticket can be opened if exact obs-pred is needed for the future.
