### ISSUE TITLE
LowRank functionality broken

### ISSUE THREAD

**Issue by dzilber** [katzfuss-group/GPvecchia#38]
The command ` vecchia_specify(locs, m=10, conditioning = 'firstm')` still does not work.  I get the following error:
```
 Error in base::log(opts$J, 2) : 
  non-numeric argument to mathematical function 
3.  get.mra.params(n, mra.options, m) at mraNN.r#93
2.  findOrderedNN_mra(locsord, mra.options, m) at vecchia_specify.R#128
1.  vecchia_specify(locs, m, conditioning = "firstm")
```

I have been using an older version of the code for my simulations but there are have been many changes to code and my simulations need to be brought up to date.

**Comment by marcinjurek** [comment]
I'm on it

**Comment by marcinjurek** [comment]
Seems like 409c126 fixed it on my end but please verify

**Comment by dzilber** [comment]
The fix works great, thank you!  Will do ;)
