### ISSUE TITLE
Towards version 1.0

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#50]
Hello @dzilber @joeguinness @wenlongG, just wanted to ping you with a quick message. I talked to @katzfuss today and it seems like it would be good if we target end of July as a deadline for upgrading the package to version 1.0. I might add some new tickets and a special label so that we mark the things that need to be resolved. But I would also want to reach out to you all and ask what do you think are the things that we need to do before then. If there is a ticket for that already, maybe please attach the v1.0 label to it. If there isn't, please open one quickly so that we know what needs to be done. I'm happy to do the maintenance work like adding tests, making sure the package install nicely etc, but there are also parts on which each one of you worked and that I'm not familiar with. Anyways, I understand you have other things going on too, but maybe just putting together a v1.0 to do list shouldn't take too much time and we can do it by the end of this week? Thanks!

**Comment by dzilber** [comment]
Stuff I have had in mind other than unit tests:
1. C++ failures causing R to crash.  Would be good if they can be avoided with low-cost checks, but I need to reproduce the problems I saw.  Typically related to cholesky decomposition failures (maybe not cpp code?).
2.  Tons of warnings coming out of source.cpp which we may be able to minimize just by cleaning the code.  Probably won't affect the end user if we create a package though.

**Comment by marcinjurek** [comment]
Re 1): I created a separate ticket. Re 2: I'm not really seeing any warnings

**Comment by marcinjurek** [comment]
@dzilber can we close this?

**Comment by dzilber** [comment]
Sure, although I have a vague feeling that the code is not ready to be marked v1.0 ;)
