### ISSUE TITLE
finalize vingettes

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#53]
We can discuss the details in a group meeting etc. but So far we have three vignettes: the general one, one for VL and one for MRA. I'd say we should consolidate it into one

**Comment by marcinjurek** [comment]
closed by accident

**Comment by dzilber** [comment]
I think it's reasonable to have one vignette for the package.  The VL vignette directly extends the original SGV vignette, so maybe if @marcinjurek just replaces the low rank approaches with more sophisticated MRA approaches for the comparison plot, we can call it "the" GPVecchia vignette.  Also it might be neat to see how well MRA does for the non-Gaussian cases, compared to low rank and VL.

**Comment by marcinjurek** [comment]
Good suggestions! I'd just add that mra does more than just replace the low-rank approach but I could simply add a few more examples. And I agree that having a consolidated vignette written in Rmarkdown is the way to go. Will work on this.

**Comment by marcinjurek** [comment]
Hey @dzilber, so I created a new vignette in the Rmarkdown format. In some spare moment, would you mind transferring your VL code there? Plots still need to be fixed, I know. Also feel free to change whatever you think is appropriate about the layout etc. This is work in progress.

**Comment by marcinjurek** [comment]
add a section on full scale approximation, mra, etc.

**Comment by dzilber** [comment]
VL example code for non-Gaussian data showing prediction and parameter estimation has been added.  Parameter estimation aborts at present but the issue may be resolved with some error checks later.
