### ISSUE TITLE
Add support for non-zero mean

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#54]

**Comment by katzfuss** [comment]
This should be part of a general parameter estimation procedure that estimates trend and covariance parameters. For simplicity, we could just estimate trend parameters using least squares, and then the covariance parameters by optimizing the Vecchia loglikelihood.
We could extend this by doing GLS estimation of the trend using the estimated covariance structure at the end.

**Comment by katzfuss** [comment]
Potentially extend this by profiling out mean and variance

**Comment by marcinjurek** [comment]
Looking for a good idea for interface design I started with `spNNGP` by Andrew Finley et al. Any other packages that I should take a look at?

**Comment by katzfuss** [comment]
geoR, lm, fields

**Comment by katzfuss** [comment]
We should also do some experiments to see if using the R package optimParallel (instead of optim() ) speeds up finding the MLEs of covariance parameters

**Comment by marcinjurek** [comment]
ok, sounds good, I'll take a look!

**Comment by katzfuss** [comment]
I wrote two user-friendly functions in the file R/vecchia_wrappers.R that do parameter (incl mean) estimation and prediction. Here is how to call them:

```
## generate data and locations
n=10^2; locs=cbind(runif(n),runif(n))
covparms=c(1,.1,.5); nuggets=rep(.1,n)
Sigma=covparms[1]*MaternFun(fields::rdist(locs),covparms)+diag(nuggets)
z=as.numeric(t(chol(Sigma))%*%rnorm(n))
data=z+1
n.p=30^2; grid.oneside=seq(0,1,length=round(sqrt(n.p)))
locs.pred=as.matrix(expand.grid(grid.oneside,grid.oneside))

## wrapper functions
vecchia.est=vecchia_estimate(data,locs,theta.ini=c(covparms,nuggets[1]))
vecchia.pred=vecchia_pred(vecchia.est,locs.pred)
```

I will make a separate ticket for enhancements (optimParallel, GLS estimation), so once the wrapper code has been added to the vignette, this ticket can be closed.
