### ISSUE TITLE
provide option ordering='none'

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#55]
For users who have already ordered their locations as desired, provide the option to set ordering='none' in vecchia_specify()

**Comment by marcinjurek** [comment]
this should be resolved now although I wasn't entirely sure if it works as you intended when prediction locations are specified. Could you please test on your end and let me know? Thanks!

**Comment by katzfuss** [comment]
ordering='none' looks good.
I suggest removing the input argument "user.order". If the user wants to use their own ordering, they can simply order their data and locations beforehand, and then call our functions with ordering='none'.
