### ISSUE TITLE
manual build fails

### ISSUE THREAD

**Issue by katzfuss** [katzfuss-group/GPvecchia#57]
I used to be able to build the package "manually" by running the following code:

```
library(GpGp)
library(Matrix)
library(RcppParallel)
library(parallel)# in order to use detectCores
library(sparseinv)
library(fields) # only needed for pred.cond='independent'

for (nm in list.files('GPvecchia/R',pattern = "\\.[RrSsQq]$")) {
  cat(nm,":"); source(file.path('GPvecchia/R',nm)); cat("\n")
}

Rcpp::sourceCpp('GPvecchia/src/Matern.cpp')
Rcpp::sourceCpp('GPvecchia/src/U_NZentries.cpp')
Rcpp::sourceCpp('GPvecchia/src/MaxMin.cpp')
```

However, I now get the following error when calling Rcpp::sourceCpp('GPvecchia/src/U_NZentries.cpp'):

> make: *** No rule to make target 'Drive/projects/vecchia_predictions/code/GPvecchia/src/Matern.o', needed by 'sourceCpp_5.dll'.  Stop.
> Warning message:
> running command 'make -f "C:/PROGRA~1/R/R-34~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" CXX='$(CXX11) $(CXX11STD)' CXXFLAGS='$(CXX11FLAGS)' CXXPICFLAGS='$(CXX11PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX11LDFLAGS)' SHLIB_LD='$(SHLIB_CXX11LD)' SHLIB="sourceCpp_5.dll" PKG_LIBS='C:/Users/katzfuss/Google' WIN=64 TCLBIN=64 OBJECTS="Drive/projects/vecchia_predictions/code/GPvecchia/src/Matern.o U_NZentries.o"' had status 2 
> Error in Rcpp::sourceCpp("GPvecchia/src/U_NZentries.cpp") : 
>   Error 1 occurred building shared library.

**Comment by marcinjurek** [comment]
I tested the almost exactly same code and it works on my computer. The only difference was that I added a line specifying the working directory after library imports, in my case this looks like 
`setwd("/home/marcin/GPvecchia")`
Maybe you could try that too?

Also, this link suggests a possible reason what might be wrong
https://support.rstudio.com/hc/en-us/community/posts/200653796-Unable-to-get-R-Studio-example-of-RCpp-to-work

**Comment by katzfuss** [comment]
The space in the path seems to have been the problem -- solved now. Thank you!
