### ISSUE TITLE
installation on windows requires some packages

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#61]
Make sure when the package is being installed these packages are included:
dequer, mvtnorm, knitr, rmarkdown

**Comment by myeongjong** [comment]
Also, I just made a minor and temporary change on  GPvecchia-package.Rd to use install_github() function in Windows 10. Now, it seems to be perfectly work.

**Comment by marcinjurek** [comment]
Let's not close it just yet. I think we do need to change whatever file it is (`NAMESPACE` or `DESCRIPTION`) to make sure these dependencies are there. I think what you fixed was a separate problem.
