### ISSUE TITLE
No protection against inadmissible parameter values

### ISSUE THREAD

**Issue by marcinjurek** [katzfuss-group/GPvecchia#66]
The following code results in data that at some iteration cause the optimization routine to crash
```{r}
library(GPvecchia)

set.seed(1989)
spatial.dim=2
n=50
if(spatial.dim==1){
  locs=matrix(runif(n),ncol=1)
} else {
  locs <- cbind(runif(n),runif(n))
}

beta=2
sig2=1; range=.1; smooth=1.5
covparms =c(sig2,range,smooth)
covfun <- function(locs) sig2*MaternFun(fields::rdist(locs),covparms)
nuggets=rep(.1,n)

Om0 <- covfun(locs)+diag(nuggets)
z=as.numeric(t(chol(Om0))%*%rnorm(n))
data=z+beta

vecchia.est=vecchia_estimate(data,locs)
```
Changing the seed to 1988 does not produce errors.

**Comment by katzfuss** [comment]
For the default Matern covariance, we could penalize strange parameter values as e.g. in Section 4.1 of https://arxiv.org/pdf/1905.08374.pdf. This would be easy to do.
Not sure what to do for other covariance functions though.

**Comment by marcinjurek** [comment]
I think the key is to make the C++ function more robust. I think it should throw an error rather than crash. This doesn't solve the problem of estimation, but does help with checking. I'm planning to see exactly when it crashes but for now I just opened this ticket so that it doesn't get forgotten. We could still pass the tests if we use the right seed. In the interim, this might be the solution

**Comment by marcinjurek** [comment]
This is a partial solve but I'm closing this ticket, as it's no longer a bug. There is now a check within `vecchia_estimate()` that ensures that smoothness is less than a threshold value. This only solves the problem in the default optimization though.
