### ISSUE TITLE
Astronomical applications and prospects for Python port

### ISSUE THREAD

**Issue by gully** [katzfuss-group/GPvecchia#79]
Hi! 👋 I am intrigued by the high performance Vecchia approximation demonstrated here, and am curious to apply some of these techniques to large-scale problems in astronomy.  I see that some of the R code wraps low-level code--- what is the prospect of a minimal Python port for some of the key methods?  Thank you again! 🙏

**Comment by marcinjurek** [comment]
Hey, thanks for reaching out. We talked about it offline but just for the sake of closing the ticket, let me say that we are not planning a full python version at this time. Some of the functionalities are available either through the [pyMRA package](https://github.com/marcinjurek/pyMRA)
