### ISSUE TITLE
new predictions & different kernels

### ISSUE THREAD

**Issue by manuelIDSIA** [katzfuss-group/GPvecchia#80]
Thanks for the great implementations! 

I would like to use your code for an application. Thereby 2 questions arose:
1) Is it possible to make new predictions after you have trained the model with the training data? Or do we have to know the prediction locations together with the training data? 
2) Is it correct that you have implemented the matern and squared exponential kernel? Have you ever tried to use for instance a periodic kernel? Where would be the starting point to implement a different kernel?

Thank you very much for your help!
Manuel

**Comment by marcinjurek** [comment]
@manuelIDSIA let me know if this helps!
